import type { KaranaInfo, NakshatraInfo, RashiInfo, YogaInfo } from '../types/eclipticBelt';

export const TITHI_NAMES = [
  '',
  'Pratipada', 'Dvitiya', 'Tritiya', 'Chaturthi', 'Panchami',
  'Shashthi', 'Saptami', 'Ashtami', 'Navami', 'Dashami',
  'Ekadashi', 'Dvadashi', 'Trayodashi', 'Chaturdashi', 'Purnima',
  'Pratipada', 'Dvitiya', 'Tritiya', 'Chaturthi', 'Panchami',
  'Shashthi', 'Saptami', 'Ashtami', 'Navami', 'Dashami',
  'Ekadashi', 'Dvadashi', 'Trayodashi', 'Chaturdashi', 'Amavasya',
];

export const TITHI_DEITIES = [
  '',
  'Brahma', 'Vidhata', 'Vishnu', 'Yama', 'Moon',
  'Karttikeya', 'Indra', 'Vasus', 'Sarpa', 'Dharma',
  'Rudra', 'Adityas', 'Kama', 'Shiva', 'Soma',
  'Agni', 'Brahma', 'Govinda', 'Pitrs', 'Nagas',
  'Vishve Devas', 'Maruts', 'Ashta Vasus', 'Aditi', 'Vishnu',
  'Brahma', 'Vishnu', 'Shiva', 'Chitragupta', 'Pitrs',
];

export const YOGA_NAMES = [
  '',
  'Vishkambha', 'Priti', 'Ayushman', 'Saubhagya', 'Shobhana',
  'Atiganda', 'Sukarma', 'Dhriti', 'Shula', 'Ganda',
  'Vriddhi', 'Dhruva', 'Vyaghata', 'Harshana', 'Vajra',
  'Siddhi', 'Vyatipata', 'Variyan', 'Parigha', 'Shiva',
  'Siddha', 'Sadhya', 'Shubha', 'Shukla', 'Brahma',
  'Indra', 'Vaidhriti',
];

export const YOGA_INFO: Pick<YogaInfo, 'meaning' | 'nature'>[] = [
  { meaning: '', nature: 'Mixed' },
  { meaning: 'Obstacle remover', nature: 'Auspicious' },
  { meaning: 'Love', nature: 'Auspicious' },
  { meaning: 'Long life', nature: 'Auspicious' },
  { meaning: 'Good fortune', nature: 'Auspicious' },
  { meaning: 'Splendour', nature: 'Auspicious' },
  { meaning: 'Danger', nature: 'Inauspicious' },
  { meaning: 'Good work', nature: 'Auspicious' },
  { meaning: 'Determination', nature: 'Auspicious' },
  { meaning: 'Thorn/Pain', nature: 'Inauspicious' },
  { meaning: 'Danger', nature: 'Inauspicious' },
  { meaning: 'Growth', nature: 'Auspicious' },
  { meaning: 'Steadfast', nature: 'Auspicious' },
  { meaning: 'Destruction', nature: 'Inauspicious' },
  { meaning: 'Joy', nature: 'Auspicious' },
  { meaning: 'Thunder', nature: 'Mixed' },
  { meaning: 'Perfection', nature: 'Auspicious' },
  { meaning: 'Great fall', nature: 'Inauspicious' },
  { meaning: 'Excellence', nature: 'Auspicious' },
  { meaning: 'Obstruction', nature: 'Inauspicious' },
  { meaning: 'Auspiciousness', nature: 'Auspicious' },
  { meaning: 'Accomplishment', nature: 'Auspicious' },
  { meaning: 'Achievement', nature: 'Auspicious' },
  { meaning: 'Auspicious', nature: 'Auspicious' },
  { meaning: 'Bright', nature: 'Auspicious' },
  { meaning: 'Creator', nature: 'Auspicious' },
  { meaning: 'King of gods', nature: 'Auspicious' },
  { meaning: 'Great danger', nature: 'Inauspicious' },
];

export const KARANA_NAMES = [
  'Bava',
  'Balava',
  'Kaulava',
  'Taitila',
  'Gara',
  'Vanija',
  'Vishti',
  'Shakuni',
  'Chatushpada',
  'Nagava',
  'Kimstughna',
];

export const KARANA_INFO: Pick<KaranaInfo, 'type' | 'nature'>[] = [
  { type: 'Movable', nature: 'Auspicious' },
  { type: 'Movable', nature: 'Auspicious' },
  { type: 'Movable', nature: 'Auspicious' },
  { type: 'Movable', nature: 'Auspicious' },
  { type: 'Movable', nature: 'Auspicious' },
  { type: 'Movable', nature: 'Auspicious' },
  { type: 'Movable', nature: 'Inauspicious' },
  { type: 'Fixed', nature: 'Mixed' },
  { type: 'Fixed', nature: 'Mixed' },
  { type: 'Fixed', nature: 'Mixed' },
  { type: 'Fixed', nature: 'Auspicious' },
];

export const RASHI_DATA: Omit<RashiInfo, 'startDegree' | 'endDegree'>[] = [
  { number: 0, name: '', westernName: '', symbol: '', element: 'Fire', ruler: '' },
  { number: 1, name: 'Mesha', westernName: 'Aries', symbol: '\u2648', element: 'Fire', ruler: 'Mars' },
  { number: 2, name: 'Vrishabha', westernName: 'Taurus', symbol: '\u2649', element: 'Earth', ruler: 'Venus' },
  { number: 3, name: 'Mithuna', westernName: 'Gemini', symbol: '\u264A', element: 'Air', ruler: 'Mercury' },
  { number: 4, name: 'Karka', westernName: 'Cancer', symbol: '\u264B', element: 'Water', ruler: 'Moon' },
  { number: 5, name: 'Simha', westernName: 'Leo', symbol: '\u264C', element: 'Fire', ruler: 'Sun' },
  { number: 6, name: 'Kanya', westernName: 'Virgo', symbol: '\u264D', element: 'Earth', ruler: 'Mercury' },
  { number: 7, name: 'Tula', westernName: 'Libra', symbol: '\u264E', element: 'Air', ruler: 'Venus' },
  { number: 8, name: 'Vrishchika', westernName: 'Scorpio', symbol: '\u264F', element: 'Water', ruler: 'Mars' },
  { number: 9, name: 'Dhanus', westernName: 'Sagittarius', symbol: '\u2650', element: 'Fire', ruler: 'Jupiter' },
  { number: 10, name: 'Makara', westernName: 'Capricorn', symbol: '\u2651', element: 'Earth', ruler: 'Saturn' },
  { number: 11, name: 'Kumbha', westernName: 'Aquarius', symbol: '\u2652', element: 'Air', ruler: 'Saturn' },
  { number: 12, name: 'Meena', westernName: 'Pisces', symbol: '\u2653', element: 'Water', ruler: 'Jupiter' },
];

export const NAKSHATRA_DATA: Omit<NakshatraInfo, 'startDegree' | 'endDegree' | 'pada'>[] = [
  { number: 0, name: '', deity: '', symbol: '' },
  { number: 1, name: 'Ashwini', deity: 'Ashwini Kumaras', symbol: 'Horse Head' },
  { number: 2, name: 'Bharani', deity: 'Yama', symbol: 'Yoni' },
  { number: 3, name: 'Krittika', deity: 'Agni', symbol: 'Razor' },
  { number: 4, name: 'Rohini', deity: 'Brahma', symbol: 'Cart' },
  { number: 5, name: 'Mrigashira', deity: 'Soma', symbol: 'Deer Head' },
  { number: 6, name: 'Ardra', deity: 'Rudra', symbol: 'Teardrop' },
  { number: 7, name: 'Punarvasu', deity: 'Aditi', symbol: 'Bow' },
  { number: 8, name: 'Pushya', deity: 'Brihaspati', symbol: 'Lotus' },
  { number: 9, name: 'Ashlesha', deity: 'Nagas', symbol: 'Serpent' },
  { number: 10, name: 'Magha', deity: 'Pitrs', symbol: 'Throne' },
  { number: 11, name: 'Purva Phalguni', deity: 'Bhaga', symbol: 'Hammock' },
  { number: 12, name: 'Uttara Phalguni', deity: 'Aryaman', symbol: 'Bed' },
  { number: 13, name: 'Hasta', deity: 'Savitar', symbol: 'Hand' },
  { number: 14, name: 'Chitra', deity: 'Tvashtar', symbol: 'Pearl' },
  { number: 15, name: 'Swati', deity: 'Vayu', symbol: 'Coral' },
  { number: 16, name: 'Vishakha', deity: 'Indragni', symbol: 'Arch' },
  { number: 17, name: 'Anuradha', deity: 'Mitra', symbol: 'Lotus' },
  { number: 18, name: 'Jyeshtha', deity: 'Indra', symbol: 'Earring' },
  { number: 19, name: 'Mula', deity: 'Nirriti', symbol: 'Roots' },
  { number: 20, name: 'Purva Ashadha', deity: 'Apas', symbol: 'Fan' },
  { number: 21, name: 'Uttara Ashadha', deity: 'Vishve Devas', symbol: 'Tusk' },
  { number: 22, name: 'Shravana', deity: 'Vishnu', symbol: 'Ear' },
  { number: 23, name: 'Dhanishta', deity: 'Vasus', symbol: 'Drum' },
  { number: 24, name: 'Shatabhisha', deity: 'Varuna', symbol: 'Circle' },
  { number: 25, name: 'Purva Bhadrapada', deity: 'Aja Ekapada', symbol: 'Sword' },
  { number: 26, name: 'Uttara Bhadrapada', deity: 'Ahir Budhnya', symbol: 'Twin' },
  { number: 27, name: 'Revati', deity: 'Pushan', symbol: 'Fish' },
];
